### ISSUE TITLE
Results are not saved with Size and Name search "Failed to save results to file key must be a string"

### ISSUE THREAD

**Issue by richrboo** [qarmin/czkawka#1137]
**Desktop (please complete the following information):**

- Czkawka version 6.1.0 gui flatpak
- OS version Fedora 38
- Terminal output[optional]:

**Bug Description**
Performing a search on Size and Name, then pressing the save button in the gui to save the results, gives an error "Failed to save results to file key must be a string" and the results are not saved, other than a broken/ empty pretty json file.

The save does work as expected with the Hash check method and the Name only method.

**Comment by qarmin** [comment]
Problem happens because it try to save results with type `BTreeMap<(u64, String), Vec<FileEntry>>`, but serde throws error `key must be a string`.

This is not supported by serde - https://github.com/serde-rs/json/issues/887 and the simplest solution is to convert BTreeMap into Vec<> which I already done in #1102
