### ISSUE TITLE
czkawka_gui.exe not launching after downloading.

### ISSUE THREAD

**Issue by RalkeyOfficial** [qarmin/czkawka#1296]
I downloaded the [7.0.0 windows gui GTK 410 version](https://github.com/qarmin/czkawka/releases/tag/7.0.0).
Which I extracted into my C:\ drive (as: `C:\windows_czkawka_gui_gtk_410`)

According to https://github.com/qarmin/czkawka/blob/master/czkawka_gui/README.md#windows
> All needed libraries should be bundled in zip (except ffmpeg which you need download and unpack to location with czkawka_gui.exe - https://ffmpeg.org/download.html#build-windows)

I needed to download FFMPEG and extract it inside the downloaded folder, but the FFMPEG zip has subfolders and the guide didn't specify what the finished folder structure looked like.

So I found this https://github.com/qarmin/czkawka/discussions/1269
Which said I needed to put the `ffmpeg.exe` and `ffprobe.exe` inside the same folder (`C:\windows_czkawka_gui_gtk_410`).
So I did that.

But now the app is now just not launching, did I do something wrong?

**Comment by Battletoadz** [comment]
ffmpeg should only be necessary for certain features of the application, like comparing pictures, audio, and video. For just ordinary hash comparison it's not necessary.

On windows I found the best way to Install for ease-of-use GUI is to use msys2, as this app is built to prefer linux, so you can run and compile with msys2 way easier than trying to use the native CLI or windows explorer

Follow the instructions here - https://www.msys2.org/#installation 
**make sure you also install the GCC tools included there via the msys2 console to ensure no issues with czkawka using this command:** `$ pacman -S mingw-w64-ucrt-x86_64-gcc`

Once you have install both these packages, simply execute this command within the msys2 console to install czkawka: `pacman -S mingw-w64-x86_64-czkawka-gui`

Note - this installs the app within your msys2 master directory. This is one of the purposes of msys2 - to act as a sort of alternative root folder to the default windows ones.

Once that is installed, you can find the final app here `\msys64\mingw64\bin\czkawka_gui.exe`

In order to reduce conflicts or errors, ensure you're running everything with administrative privileges, and allow msys2 through your firewall before installing anything.

**Comment by RalkeyOfficial** [comment]
That worked thank you.
