### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by jannuary** [qarmin/czkawka#136]
"Czkawka" is pretty weird - it isn't particularly descriptive of the app, and rather hard to pronounce for pretty much everyone not speaking polish, as every online post about it indicates.

Here are some candidates that represent the app's domain better: 

* Similia
* Cliché
* Shredder
* Housekeep(er)
* Ditto
* Doppelganger 
* Expunger

**Comment by Cantuccini-Lori** [comment]
i really like the program and I am glad, that you did the work to program it from the scratch! 
The nae is imposible for me to remember, when I work on console. So maybe a change would be good:

fslint-ng
fsdupe
dupefinder
dupeking
superdupe(r)
dublicater
dupejanitor
dupecleaner
dupecontrol#
etc

**Comment by xxcriticxx** [comment]
czkawka = hiccup

Maybe the English variant of the word will help you?

**Comment by jannuary** [comment]
> czkawka = hiccup
> 
> Maybe the English variant of the word will help you?

"Hiccup" doesn't really describe what the app does or is about, neither doews "Czkawka".
I'd suggest taking a look at this blog post: [Naming Your App - Space and Meaning](https://blogs.gnome.org/tbernard/2019/04/26/naming-your-app/)

**Comment by Jakeukalane** [comment]
**Comment**: Is not only bad for pronunciation for anglophones. Is for everyone not polish. My proposed solution if this is not done would be to do an alias or a soft link of the executable. Maybe I will call it "hipo", as seems everyone is trying to make a stand about its own language...

**Comment by arteme** [comment]
A comment in support of the current name -- it stands out! :grin: Seriously, I only have to type `cz<TAB><ENTER>` to run the app because all other tools are named in English.

**Comment by qarmin** [comment]
At the moment, I do not plan to change the name of Czkawka, because the name has already more or less is in people's minds.

The new name should go with a new quality, so it is better to wait for a new additional frontend to be developed alongside the current one (at least until it is fully functional) and give it a catchy name(will be available in this repository as different module).

So far, the only obstacle is the lack of support for GTK 4 in Glade because I do not want to create a program in GTK 3 and rewrite it later.

**Comment by dandv** [comment]
I've also been perplexed by the name, and can never remember to type it properly. "cz--what? Was it made in Czechia?" went through my mind. When I saw it at the top of this [comparison matrix](https://github.com/pixelb/fslint/issues/173) I didn't even take it seriously.

I've read the [README section about the name](https://github.com/qarmin/czkawka#name). Fun experiment, but I don't think it was a good idea.

**Comment by SpheeresX** [comment]
This name is beautiful, don't remove it lmao

**Comment by loloi91** [comment]
Hey

**Comment by cyberlionx** [comment]
> The nae is imposible for me to remember, when I work on console. So maybe a change would be good

In the interim you could set an alias, yes?

**Comment by cyberlionx** [comment]
In English it looks like zh-caca... whish is unfortunate as caca is a common term for faeces

I think I'll alias it as RustLint since my understanding is that it's basically FSLint but in Rust and actively maintained. 

@qarmin The FSLint website actually has a note directing people to this project, which is how I found it. Not sure when they did that but I suspect a whole lot of FSLint users (especially any that also use Windows) will be effectively replacing FSLint with this software. So you've that to look forward to.

**Comment by Matt-Deacalion** [comment]
I love the name. For me, it perfectly captures it's function... repeating files are like the hiccups.

PS: thank you for creating this tool, I used it last night and it worked perfectly!

**Comment by qarmin** [comment]
The name is too integrated into the application to change.

As for the new gui, probably a lot of people won't like it, but I've named the app Krokiet.

Yes, this name is also strange but because it's my personal project I decided there was no point in giving a fancier name as it's not aimed at any companies or the commercial market and it's something the project stands out with.
