### ISSUE TITLE
CLI has different output from GUI

### ISSUE THREAD

**Issue by smivv** [qarmin/czkawka#254]
Hello,

I checked CLI tool and GUI tool on the same folders and they have different results:

CLI found 0 similar images, GUI found 100+.

I can't share images, but I already see that I am unable to choose Similarity option in CLI and also unable to save list of files from GUI.

Would be also good to save list of files in json format with additional info.

**Comment by qarmin** [comment]
Saving to file was not working because code was commented(probably I wanted to finish implementing similar image tool before, but I forgot to uncomment it later).

I can't reproduce different results in GUI and CLI.
They use exactly same backend so most of code is shared between this two apps and it is very unlikelly that they would have different results.

To set similarity option in CLI you must use `-s` e.g.
```
czkawka_cli image -d /home/rafal/Projekty/ -m 16384 -s veryhigh
```

**Comment by smivv** [comment]
I am currently using 2.3.0 since I found only this prebuilt binaries for Mac and seems like it does not support `-s` flag.

Are there any other differences between CLI and GUI? Maybe I forgot to add some flags.

**Comment by smivv** [comment]
well, I just understood that I've used different functions 😂 duplicated and similar images
