### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [qarmin/czkawka#290]
```
############### ERRORS ###############
Optimize Directories ERROR: Excluded directories overlaps all included directories.
```
Czkawka 2.3.0
Arch

**Comment by qarmin** [comment]
This is valid error in most situations(not sure if at all)
It happens when Czkawka can't find any folder to scan.
E.g.

Included directories:
```
/home/user/folder2
/home/user/folder1
```
Excluded directories
```
/home/user
```
So all included directories are inside excluded directories so it means that there is no available folder to take and start search

**Comment by KonoromiHimaries** [comment]
How to fix it?

**Comment by qarmin** [comment]
Depends what you want to do.
The easiest is to reset in option window settings(but this only works when something was messed manually)
It is also possible to remove `Excluded items`, because they can sometimes overlap with selected directories.
In included directories must exists at least one directory to search

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
What https://github.com/qarmin/czkawka/issues/290#issuecomment-798649045 states should be included in the error-message. I had to search for this problem for a while because the error was too nondescript despite the problem being so simple.
