### ISSUE TITLE
Add a `find -xdev` equivalent

### ISSUE THREAD

**Issue by sseering** [qarmin/czkawka#31]
Add a `find -xdev` equivalent. Add a function to only search on one filesystem.

**Comment by qarmin** [comment]
I'm not sure if I understand this correctly what this argument do.

By default `find` search also places at which points symbolic links, and `-xdev` prevents from doing this?

If yes, then this issue can be closed because Czkawka just ignore symbolic links, because they will allow to break tree hierarchy of file system, and will force to remove some directory optimizations and it will require additional step with removing duplicated same files with identical path.

**Comment by sseering** [comment]
`-xdev` will make `find` never leave the filesystem it started on. `czkawka` should do that too. 

**Example:**  

-  `/`  is on `/dev/sda1`
-  `/usr/share/databases` is on `/dev/sda2`

then a search starting in `/usr` would look at all files recursively in `/usr/` but at no files in `/usr/share/databases`.

**Why its useful**

In the current `czkawka` version when I want to search for duplicate files in `/` device then it would search `/proc` and `/dev` and `/sys` too. It doesn't make sense to search in these so `/proc` and `/dev` and `/sys` are in the excluded dirs by default.

But it also searches in `/tmp` which is wrong because its tmpfs so I add `/tmp` to the excluded dirs too and restart search.

But it also searches in `/run` which is wrong because its tmpfs so I add `/run` to the excluded dirs too and restart search.

But it also searches in `/boot/efi` which is wrong because its the EFI ROM so I add `/boot/efi` to the excluded dirs too and restart search.

But it also searches in `/mnt/nfs` which is wrong because its a network filesystem so I add `/mnt/nfs` to the excluded dirs too and restart search.

And so on .... .

Exclusion lists are like chasing an imperfect solution here. Limiting the search to one filesystem is really useful here to automatically exclude all of `/proc` and `/dev` and `/sys` and `/run`  and ...  and so on without needing to work on a list that will never be perfect.

**Comment by qarmin** [comment]
For anyone - https://doc.rust-lang.org/std/os/unix/fs/trait.MetadataExt.html#tymethod.rdev - this may be helpful
