### ISSUE TITLE
make hashing on gpu and not cpu

### ISSUE THREAD

**Issue by TomerGamerTV** [qarmin/czkawka#344]
can you make the hashing process on GPU and not CPU so it will run faster and won't freeze the pc?

well it's not that it's freezing my pc but just in case

**Comment by qarmin** [comment]
I profiled app and low hashing performance is caused mostly by two things:
- Opening image - needs to load image from disk and save to proper structures to memory
- Resizing image to 8x8 - scale image to lower amount of pixels to be able to use it for hashing

Calculating hash doesn't use too much CPU.

So for now hashing(I don't talk about image resizing which is a part of hashing) isn't bottleneck and doesn't need for now any GPU implementation

Opening and resizing image is the slowest part, but since it have been taken directly from `image-rs` library, GPU support can be only implemented there.

**Comment by qarmin** [comment]
Closing, since this issue should be created in `image-rs` library(in case of GPU support of resizing).
