### ISSUE TITLE
Windows Security error message

### ISSUE THREAD

**Issue by scorpioraj** [qarmin/czkawka#369]
Hi

When I am selecting all the files and right clicking I get this error message. Any idea why I am getting this error message?
![Capturef54553](https://user-images.githubusercontent.com/83529373/119267808-c0318680-bc0d-11eb-8926-1102660b52c9.JPG)

Secondly, this program seems to be a massive program- 6300 files and 491 folders. Nearly 100 mb files. I am using Windows 8.1 x64. Am I right here or ?

![Capture54353453453](https://user-images.githubusercontent.com/83529373/119267859-fec74100-bc0d-11eb-9542-bdc4cef68b20.JPG)

Thanks

**Comment by qarmin** [comment]
This is only warning that Windows doesn't recognize Czkawka since it doesn't have certificate(which costs money, so it is very unlikely that in future this will fixed).

Only `czkawka.exe` file is created by this repository, rest of files comes from GTK(it is library to create user interface).
As I wrote in instruction, it is possible to be able to run this app without rest of files, but this will require to to install GTK Runtime from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

**Comment by alexislefebvre** [comment]
How did you install it? The file `windows_czkawka_cli.exe` from the [releases page](https://github.com/qarmin/czkawka/releases) weights 3.29 MB.

**Comment by scorpioraj** [comment]
I used the zip file and transferred that to a folder. While transferring I found of these much files, so was bit curious about it. Exe file will be less, but the accompanying files is large

**Comment by alexislefebvre** [comment]
Oops, the `windows_czkawka_cli.exe` is only the CLI, that's why it's small. According to the above answer from qarmin, these files are mandatory to run the GUI.

**Comment by qarmin** [comment]
There is unofficial Chocolatey package which don't have such problem
