### ISSUE TITLE
Enhancement Request: Raw Image Format

### ISSUE THREAD

**Issue by cfelicio** [qarmin/czkawka#411]
Hi There,

Wondering if there are any plans for a future release to include raw image support? E.g. .cr2 (cannon), .nef (Nikon), etc.

Thanks for the awesome tool!

**Comment by orthorhombic** [comment]
+1 for the raw or dng image support. And thank you @qarmin for this awesome software!

https://github.com/pedrocr/rawloader/ seems to be a library that could be used to extract raw image content. I would think that could be plumbed into how you're already handling tiff files.

Not sure how universal it is, but the answer here uses imagemagik and dcraw to pull tiff content out of a dng.
https://photo.stackexchange.com/questions/79368/how-and-why-does-vuescans-tiff-and-dng-output-differ

Unfortunately I don't speak Rust, otherwise I'd try to help more.

**Comment by cfelicio** [comment]
Thanks  so much!
