### ISSUE TITLE
Error building on Ubuntu 20.04 (focal)

### ISSUE THREAD

**Issue by jhonny-oliveira** [qarmin/czkawka#418]
Hi!

I'm unable to build the latest version of czkawka (3.2.0) on Ubuntu 20.04 (focal). On Ubuntu 21.04 (hirsute) it builds fine. I think this is related to the version of cargo: focal - cargo 0.47.0; hirsute - cargo 0.52.0. If so, would it be possible to make a patch to make it work with focal?

I'm attaching the build log for further investigation: [build_log.txt](https://github.com/qarmin/czkawka/files/6984912/build_log.txt).

Thank you!
Jhonny @xtradeb.net

**Comment by qarmin** [comment]
This is mostly caused by rustc(1.54.0 latest stable - 1.47.0 Ubuntu 20.04).

Latest version is required by gtk, arrayvec(indirectly) and others because adds few interesting features like const generics.

I tried to downgrade some dependencies(indirect) but failed to do it(looks that cargo can only upgrade things properly)

For now the lowest version of Rust which allows to compile app is 1.51.0, so probably waiting for Ubuntu to upgrade rust compiler is the only option.

**Comment by jhonny-oliveira** [comment]
Thank you @qarmin! I have pushed it to hirsute. If at some point the build also works for focal, then I will upload it too.

Cheers!

**Comment by psyll** [comment]
a

**Comment by qarmin** [comment]
https://packages.ubuntu.com/search?suite=focal&arch=any&searchon=names&keywords=rust

**Comment by jhonny-oliveira** [comment]
Thank you Rafal!

I have update the package and it is now also available for Ubuntu focal: https://xtradeb.net/apps/czkawka.

Could you please update the PPA installation instructions to, or inline with: https://xtradeb.net/wiki/how-to-install-applications-from-this-web-site?

Cheers!
