### ISSUE TITLE
Strange false positive

### ISSUE THREAD

**Issue by jasontitus** [qarmin/czkawka#429]
I am seeing a number of very odd false positives.  Here are a few examples.  I see many of these running current HEAD on Ubuntu 21.04.

![IMG_0625(10)](https://user-images.githubusercontent.com/870238/132105119-3a210b92-bfb0-4e22-80f7-8c8d89ef10f2.jpg)
![IMG_1230(3)](https://user-images.githubusercontent.com/870238/132105122-3335c6db-dbe2-4e82-847e-c5abe547663a.jpg)
![IMG_3448-edited(1)](https://user-images.githubusercontent.com/870238/132105124-1ff2a629-8a8d-4b24-9985-58043a462b90.JPG)

**Comment by jasontitus** [comment]
If it wasn't clear - those were all in a dupe cluster together.  Seems like a pretty significant issue.  These were in addition to a few actual dupes as well.

**Comment by qarmin** [comment]
I think that this is mostly limitation how Gradient algorithm is implemented.
In current stable version image is resized to 8x8 image, which probably looks very similar to even different images.
Also I think that all colours are converted to gray scale.

Now (since  96e7af0d2549def72d33ebe9b47da9bdcaaf007c) hashes 16x16 are supported, so with 4x more info there should be less false positives.
Also new algorithms were added, because default Gradient hash sometimes not works properly for all types of images so other may works better for specific images(e.g. BlockHash don't resize image)

So such false positives are expected, but different algorithms and bigger hash size
