### ISSUE TITLE
[Question] Does the Flathub version of the upcoming v4.0 use Flathub's Freedesktop ffmpeg?

### ISSUE THREAD

**Issue by puelp** [qarmin/czkawka#523]
I am excited to test out the similar-videos feature when 4.0 is released.

However, reading Instruction.md, I saw that "To work require FFmpeg, so it will show an error when it is not found in OS".

Is that warning just for packaged versions of Czkawka, or the Flathub version as well?

Because for people like me who install media players from Flathub that utilize Flathub's Freedesktop library (which includes ffmpeg, I think), there is no need to install a system-level ffmpeg package.

Will the Flathub version of Czkawka do that as well?

**Comment by qarmin** [comment]
Looks that without ffmpeg installed on OS, flatpak build runs fine, but I don't know if I correctly setup everything so this is build which I tested - https://github.com/flathub/com.github.qarmin.czkawka/pull/10

This error is shown every single Czkawka build(I don't "personalize" flatpak and snap builds) that don't have access to ffmpeg in its path.

Now I have problem with Snap, because don't find ffmpeg in PATH due sandboxing

**Comment by qarmin** [comment]
After release I see that ffmpeg version from flatpak is used, so it is not needed in host os
