### ISSUE TITLE
Double click to open image fails 90% of the time

### ISSUE THREAD

**Issue by NomarCub** [qarmin/czkawka#577]
Double clicking on a result in Similar Images opens the image in the default app sometimes, but fails most of the time.
I'm running 3.3.1 on Windows.

**Comment by qarmin** [comment]
This is probably fixed in latest version, binaries can be tested here - https://github.com/qarmin/czkawka/actions/runs/1699392960
Previously apps were opened in same thread as Czkawka.
Currently files are opened in new thread(disadvantage is that there is not shown an error when failed to open path)

**Comment by NomarCub** [comment]
Thanks, it works in the latest version!
When can we expect a release?

(By the way, I found triple clicking to work well enough in the current version.)

**Comment by qarmin** [comment]
Probably in next wext wek
