### ISSUE TITLE
Similar videos function not working on windows gui

### ISSUE THREAD

**Issue by Ciberbago** [qarmin/czkawka#596]
Hello! I'd like to start saying that this program is great for finding similar images, very accurate and helpful.
I tried to use the similar videos function too, but it did not work, it said this:

############### ERRORES(2) ###############
No se puede encontrar la instalación correcta de FFmpeg
Los Videos Similares no funcionan actualmente con el snap, si quieres ayuda mira - ⁨https://github.com/snapcrafters/ffmpeg/issues/73⁩

It's in spanish but I guess you already know what is about.
I have FFmpeg on my machine, but the program can't find it. Would be great if we had the option to specify the FFmpeg installation path so we can use the similar videos function in windows :D

**Comment by minicoz** [comment]
Hola! 

I fixed this by downloading (On Windows) The full ffmpeg release. This will include a folder called /bin with a file called ffmpeg.exe

What you need to do is add that to your environment variables so that you can call ffmpeg from any cmd terminal and it will find the ffmpeg.exe

Basically I extracted the .zip that contained the ffmpeg application, then I went to "Edit the system Environment Variables" on windows, added a new variable to PATH which points to ffmpeg.exe folder path that I had previous extracted. 

Then I tested it on a regular cmd and restarted czkawka gui and it works.

**Comment by Ciberbago** [comment]
I'm very thankful. This worked nicely. 
I appreciate the "Hola" at the beginning, lol

**Comment by cscott0108** [comment]
It took me several tries but for Czkawka, the environmental variable should be ffmpeg, not FFmpeg, not ffmpeg.exe. Just ffmpeg. That resolved the issue for me.

**Comment by SafetyCar** [comment]
I was having problems on windows because it was using ffmpeg from an unexpected location (ImageMagick).
I could find the real place with the command "where ffmpeg" and I saw that the place didn't have ffprobe.
After making sure that ffprobe was accessible it started working.
