### ISSUE TITLE
Custom selection doesn't do anything.

### ISSUE THREAD

**Issue by Misaria** [qarmin/czkawka#600]
It's very fast and from what I can tell accurate even though the files were missing a lot of information; so good job!

A couple of days ago I tried v3.3.1. and custom selection didn't do anything.  
I just tried out this version (4.0.0) and unfortunately it's still not working no matter what folder depth or setting I try.  

The file structure is:  
Drive X> Folder A> Multiple Folders>Multiple Folders>Files.
And Drive Y> Folder A> Multiple Folders>Multiple Folders>Files

The other selections (newest, smallest, etc.) work fine.

I just tested it with:
X:\Folder>Files
Y:\Folder>Files
Still doesn't select anything.

How do I select all the files from one drive, or one folder with all the subfolders included?

**Comment by qarmin** [comment]
Using X* in Path should work just fine

![Zrzut ekranu z 2022-01-24 09-24-43](https://user-images.githubusercontent.com/41945903/150747304-f5dd75a6-953d-492e-ad39-7a0d617d118e.png)

**Comment by Misaria** [comment]
Thanks, though it's not working for me.

One thing that worked is to use Regex Path + Name: Y*  
With "Don't select all records in this group" checked.
Then it selected all the files on Y:\
If "Don't select all records in this group" is unchecked it selects all the files on both the X and Y drive; even though the files don't have a X or Y in their name.

One problem for me, and it's why I decided to try this program, is that I used two broken zip files, and recovered the data from both of them; so it will be the same file structure.  
If I did get the Path selection to work it wouldn't select files based on the drive they're on?

I don't know if this is possible as a selection, but my goal was to put the recovered data on two drives to keep the folder path the same, then run the program to find duplicate images, by similarity (which it did a great job at), that contain less of the image (glitched looking, etc.) and then select the images that is the most incomplete; and remove them.  
The files have the same size even though one image is 100% and the other is just 10%.   
Don't think any program has that sort of option?

Suggestion to add things like:
Select all files in this folder that has a duplicate anywhere else
Select all files that duplicate files in this folder

Again, thanks!

**Comment by RuneDemomn** [comment]
Yeah I can't get custom working either with path or regex+path. I can only select the whole drive using this method but I have duplicates in the same drive and I only want to delete a specific folders duplicates.

**Comment by RedAero** [comment]
Same, nothing seems to work. Backslash, forward slash, the full path, it never selects anything.

**Comment by elsatch** [comment]
I am having the same issue but I suspect it is happening because we are using Windows file routes.

All examples in czkawka show linux/mac routes like /home/dirA/dirB but in Windows we would have C:\dirA\dirB. So I assume the program is not parsing the Windows routes correctly.

Fortunately, I made it work using the Custom Regexp path and name. In my particular case, I wanted to select all files located under folder J:\dropbox. 

I used the following regexp to filter: `^J:\\dropbox\\` 

That means select all paths starting by J: followed by backslash dropbox backslash.
 
Note: I had a copy of files at a folder called dropbox-replica that I would like to keep so I figured out in this way, these would not be selected. In my case, it worked!

**Comment by sukhdevgill** [comment]
> 

Yep, this is the solution.

**Comment by mimentum** [comment]
On Win 10 using release v4.0.0, I am unable to select anything with the custom selection tool, using any of the regex implementations or solutions above such as `^J:\\dropbox\\` example as given above. 

Trying something like `/^[A-Z]:\\(?:\w+\\?)*$/` where _[A-Z]_ is replaced with the drive letter, does not work. 

No itterations are working for `^_[A-Z]_:\\` followed by different combinations of quadruple or double or single forward & backslashes, full directory names or **_*_** (asterisk) or **?** wildcard characters.

**Comment by marcellonovak** [comment]
Having the same issue, trying to select everything under `C:\Users\Administrator\Desktop\unsorted`, but `^C:\\Users\\Administrator\\Desktop\\unsorted` does not work under "Path", and `^C:\\Users\\Administrator\\Desktop\\unsorted\\*` does not work under "Regex + Name".
Running windows.

EDIT: `^C:\\users\\administrator\\desktop\\unsorted` with "Don't select all records in group" worked with "Regex Path + Name"

**Comment by Lumpapps** [comment]
I believe the problem lies in the capitals. I used a path named E:\Dropbox\Projects and that didn't work. When I rewrote it like this: E:\dropbox\projects it worked. This looks consistent with Regex where it also is written in lower cast. It doesn't seem to be consistent on my trail and error but it is worth a try
