### ISSUE TITLE
Low CPU utilization during image hash comparison

### ISSUE THREAD

**Issue by gotr3k** [qarmin/czkawka#679]
Hi, was just wondering why is the CPU utilization low during image hash comparison phase of the scan? Every other phase has some obvious bottleneck (disk/cpu at max), but this one confuses me. How is the comparison implemented? Great work btw!

**Comment by qarmin** [comment]
For now the main bottleneck is that algorithm works only on one thread 

Code - https://github.com/qarmin/czkawka/blob/c88d347e0093ba0af47b2fc8714e67cced36cc89/czkawka_core/src/similar_images.rs#L718-L836

Adding multithreading to it is not so easy, because finding objects is related to list of excluded items, that was modified in previous iterations, so simple and fast solutions of dividing tasks to 4,8 or 16 parts are not available here.

But even with support of multiple threads, it would be still quite slow because with big number of hashes, each hash needs to be compared with every else multiple times.
