### ISSUE TITLE
Allow selecting phone as a directory

### ISSUE THREAD

**Issue by nirvdrum** [qarmin/czkawka#76]
I don't know the Windows API well enough to tell if this is possible, but when I mount my phone on Windows 10, it appears under "This PC" but not as a mounted drive. I'd like to be able to find pictures and videos on my phone that are already backed up to my NAS so I can clear up space occupied by the duplicates.

**Comment by qarmin** [comment]
Sadly phones are not mounted as normal external disk, so apps like Czkawka are unable to check it.
My phone on Linux is mounted in

`/run/user/1000/gvfs/mtp:host=HUAWEI_DRA-LX9_9FT0613905560/
Pamięć wewnętrzna`
or
`mtp://HUAWEI_DRA-LX9_9FT0613905560/Pami%C4%99%C4%87%20wewn%C4%99trzna`

this clearly shows that is OS create temporary directory which are is accessible only from explorer/nautilus/nemo etc. but not other programs.

If someone want, to implement this I would be happy, but I never saw application which worked on file system on phone, so I will close issue, because this is enhancement which will be never(probably) added.

**Comment by hackhowtofaq** [comment]
This problem exists for mount points on Linux as well

**Comment by queeup** [comment]
I am trying to compare local and ssh folder mounted with `nautilus` in gnome with czkawka and hitting this problem.

```
############### MESSAGES(2) ###############
Loaded from cache ⁨691⁩ entries
Saved to file ⁨693⁩ cache entries
############### WARNINGS(1) ###############
Directories:  Provided folder path must exist, ignoring ⁨/run/user/1000/gvfs/sftp:host=libreelec,user=root/storage/backup/
```

As far as I can tell `Shotwell` ptoto program allow me to import from gvfs directories. It read the directory. Maybe czkawka do that like that program?
