### ISSUE TITLE
Is the any planning to support JXL?

### ISSUE THREAD

**Issue by chchia** [qarmin/czkawka#781]
recently more and more images are provided in JXL format.
https://fileinfo.com/extension/jxl#:~:text=A%20JXL%20file%20is%20an,JPG%20and%20.

do you have any plan to support this format?

thank you.

**Comment by qarmin** [comment]
It will be supported when  `image-rs` library which I use to support images will handle such files
Relevant issue - https://github.com/image-rs/image/issues/1648

**Comment by Quackdoc** [comment]
as an update to this since it came up in a circle im in, JXL seems unlikely to be included in image-rs due to the specification papers, being paywalled (note this is different from the format itself being nonfree). I did make a PR for JXL support in image-rs that should be mostly compatible if someone wanted to rebase the PR and build image-rs against it, but it doesn't support GIFs yet, and quite frankly im not super interested in doing any more work on the mater myself. 

so unless something changes, if a user of czkawka wants JXL support, it will need to be implemented within czkawka itself. JXL-Oxide does not currently provide a "image-rs interop" function, but it won't be too hard to get it working. and there was some possibly asked. Releveant links provided below


https://github.com/image-rs/image/issues/1979
https://github.com/image-rs/image/pull/1945
https://github.com/tirr-c/jxl-oxide/issues/162

**Comment by jingyitian** [comment]
JXL is now officially one of the photo format on newest iPhones. it would be unfortunate if the support is not available.
