### ISSUE TITLE
5.0.2 unsupported on Debian Bullseye (due to libc >= 2.32 dependency)

### ISSUE THREAD

**Issue by jkaberg** [qarmin/czkawka#823]
Would it be possible to support 2.31? See output:

```
root@dunder:~# /root/czkawka dup -d /tank --delete-method HARD --file-to-save /root/czkawka_out.txt
/root/czkawka: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /root/czkawka)
/root/czkawka: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/czkawka)
/root/czkawka: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/czkawka)
root@dunder:~# ldd --version
ldd (Debian GLIBC 2.31-13+deb11u3) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
root@dunder:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
root@dunder:~#
```

**Comment by qarmin** [comment]
Only Czkawka pre-build binaries require libc 2.35 and there is no hard requirement about version of this library 
The problem is that only quite new versions of OS contains by default GTK 4.6(e.g. Ubuntu 22.04) which is required to compile and use app.
If you enough time and motivation to compile manually GTK 4.6 and Czkawka on your computer, then everything should works fine even on Debian 9(this could be simplified if GTK 4 developers would provide docker image with library and Ubuntu 18.04/20.04)

**Comment by jkaberg** [comment]
I'm running czkawka on an headless server with no GUI - surely the CLI tool shouldn't have hard dependencies on an GUI framework? 

As per your suggestion - sure, I might try that

**Comment by daniporr** [comment]
I think this is the same problem I mentioned in #810 (see https://github.com/qarmin/czkawka/issues/810#issuecomment-1228959386 and https://github.com/qarmin/czkawka/issues/810#issuecomment-1237282461).

**Comment by daniporr** [comment]
Any news on this?
