### ISSUE TITLE
Checking for broken files fails with PDF Documents

### ISSUE THREAD

**Issue by nineff** [qarmin/czkawka#898]
The check for broken files yielded only PDFs, all of which are not broken.
In some cases, the PDF-rs library reported a crash, in others there's a "Try at ..." reported.
See attached screenshot.
![Screenshot 2023-01-19 144436](https://user-images.githubusercontent.com/3100873/213459139-fc1fee49-a3eb-45c4-9617-e26d0c355688.png)
[Long Harry.pdf](https://github.com/qarmin/czkawka/files/10457275/Long.Harry.pdf)
I've also uploaded one of the PDFs where the lib crashes.

**Comment by qarmin** [comment]
I opened issue here - https://github.com/pdf-rs/pdf/issues/162 - this message is really unclear

Crashes should be fixed in master branch, due updating pdf to 0.8 version.

Not always errors means that file cannot be opened, sometimes pdf use invalid tags, which not change document appearance or ability to open.

**Comment by qarmin** [comment]
Latest version added options to silence some non critical bugs and this will be available after merging - https://github.com/qarmin/czkawka/pull/894

**Comment by s3bk** [comment]
pdf 0.8.0 has been released.
the "try at" error is basically an annotation of where the error occured.
